### PR TITLE
Feature/report

### PR DESCRIPTION
**Pull request by adgarciaar**

### CODE REVIEW

**Review by nicolasmira101 — APPROVED** [review]

**Review by miguelgz36 — APPROVED** [review]

**Comment by orozcojuan1998** [comment]
Is your branch updated with the latest changes on GUI/improvements?

**Comment by adgarciaar** [comment]
> 
> 
> Is your branch updated with the latest changes on GUI/improvements?

no

**Comment by orozcojuan1998** [comment]
> > Is your branch updated with the latest changes on GUI/improvements?
> 
> no

Can you update your branch?

**Comment by adgarciaar** [comment]
> 
> 
> > > Is your branch updated with the latest changes on GUI/improvements?
> > 
> > 
> > no
> 
> Can you update your branch?

Merged

**Review by orozcojuan1998 — APPROVED** [review]

**Pull request merged**
